name: Update Page Views

on:
  schedule:
    - cron: "*/5 * * * *"             # 每小時
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0             # 允許 pull/rebase

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Fetch hits and build JSON
        shell: bash
        run: |
          fetch_hits () {
            URL="$1"
            TMP=$(mktemp)
            curl -fsSL "$URL" -o "$TMP" || echo "" > "$TMP"
            grep -oE '>[0-9]+' "$TMP" | tail -n1 | tr -dc '0-9'
          }

          HOME=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/index.html.svg")
          FCG=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/FCG.html.svg")
          FMG=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/FMG.html.svg")
          TORII=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/Torii.html.svg")
          UPDATED=$(date -u +%FT%TZ)

          jq -n \
            --argjson home "${HOME:-0}" \
            --argjson fcg "${FCG:-0}" \
            --argjson fmg "${FMG:-0}" \
            --argjson torii "${TORII:-0}" \
            --arg updated "$UPDATED" \
            '{Home:$home, FCG:$fcg, FMG:$fmg, Torii:$torii, updated_at:$updated}' > views.json

      - name: Commit & push (with rebase / retry)
        shell: bash
        run: |
          # 若 views.json 沒變就直接結束
          if git diff --quiet views.json; then
            echo "No changes in views.json"
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 先確保本地分支和遠端同步，再提交
          BRANCH="${GITHUB_REF_NAME:-main}"
          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git pull --rebase origin "$BRANCH"

          git add views.json
          git commit -m "Update views.json" || exit 0

          # 嘗試推送；若被拒絕（非快轉），再 pull --rebase 一次後重試
          if git push origin "$BRANCH"; then
            echo "Pushed."
          else
            echo "Push rejected, rebasing then retrying..."
            git pull --rebase origin "$BRANCH"
            git push origin "$BRANCH"
          fi
