name: Update Page Views

on:
  schedule:
    - cron: "*/5 * * * *"        # 每 5 分鐘；要改每小時 → "0 * * * *"
  workflow_dispatch:              # 可手動觸發

permissions:
  contents: write                 # 允許用 GITHUB_TOKEN 推回 repo

concurrency:
  group: update-views
  cancel-in-progress: true        # 避免多次同時執行互相踩到

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # 需要完整歷史以便 rebase

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Fetch hits and build JSON
        shell: bash
        run: |
          set -euo pipefail
          fetch_hits () {
            URL="$1"
            TMP=$(mktemp)
            curl -fsSL "$URL" -o "$TMP" || echo "" > "$TMP"
            # 從 SVG 提取徽章右半部數字
            grep -oE '>[0-9]+' "$TMP" | tail -n1 | tr -dc '0-9'
          }

          HOME=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/index.html.svg")
          FCG=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/FCG.html.svg")
          FMG=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/FMG.html.svg")
          TORII=$(fetch_hits "https://hits.sh/oro1081111.github.io/oro-games/Torii.html.svg")
          UPDATED=$(date -u +%FT%TZ)

          jq -n \
            --argjson home  "${HOME:-0}" \
            --argjson fcg   "${FCG:-0}"  \
            --argjson fmg   "${FMG:-0}"  \
            --argjson torii "${TORII:-0}" \
            --arg updated "$UPDATED" \
            '{Home:$home, FCG:$fcg, FMG:$fmg, Torii:$torii, updated_at:$updated}' > views.json

      - name: Commit & push with rebase/retry
        shell: bash
        run: |
          set -euo pipefail

          # 若 views.json 無變更則直接結束
          if git diff --quiet views.json; then
            echo "No changes in views.json"
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH="${GITHUB_REF_NAME:-main}"
          git add views.json
          git commit -m "Update views.json" || true

          attempt_push () {
            git fetch origin "$BRANCH"
            git pull --rebase --autostash origin "$BRANCH" || true
            git push origin HEAD:"$BRANCH"
          }

          # 最多重試 3 次，避免 race condition
          for i in 1 2 3; do
            if attempt_push; then
              echo "Pushed on try #$i"
              exit 0
            else
              echo "Push failed on try #$i, retrying..."
              sleep 2
            fi
          done

          echo "Giving up after 3 tries."
          exit 1
